"""nuevo

Revision ID: 279314d5a5f9
Revises: 
Create Date: 2021-03-14 02:15:50.577861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '279314d5a5f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('contrasenia', sa.String(length=10), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.Column('direccion', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisosxUsuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('permiso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], )
    )
    op.drop_table('prueba')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prueba', mysql.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('permisosxUsuarios')
    op.drop_table('usuarios')
    op.drop_table('permisos')
    # ### end Alembic commands ###
