"""nuevo algo

Revision ID: 446d6e27917e
Revises: 279314d5a5f9
Create Date: 2021-03-14 02:19:09.476879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446d6e27917e'
down_revision = '279314d5a5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('apodo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'apodo')
    # ### end Alembic commands ###
