"""se agrego username

Revision ID: 76f5cf5e061e
Revises: 
Create Date: 2021-03-21 01:26:32.137210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f5cf5e061e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('mail', sa.String(length=60), nullable=True))
    op.add_column('usuarios', sa.Column('username', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'username')
    op.drop_column('usuarios', 'mail')
    # ### end Alembic commands ###
