"""Se agregaron los campos username y mail

Revision ID: 9ec4ee498a00
Revises: 
Create Date: 2021-03-20 21:18:56.582550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec4ee498a00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('mail', sa.String(length=60), nullable=True))
    op.add_column('usuarios', sa.Column('username', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'username')
    op.drop_column('usuarios', 'mail')
    # ### end Alembic commands ###
